### ISSUE TITLE
Calendar localization

### ISSUE THREAD

**Issue by bummzack** [praxisnetau/silverware-calendar#2]
There seems to be no way to localize the calendar. 
In the CMS, it would ideally pick up the locale-setting of the currently logged in user and apply that. For frontend usage, a config-option could be used (currently, setting a `'locale'` via `setCalendarConfig` has no effect, most likely because the localization files aren't bundled or exposed).

**Comment by colintucker** [comment]
Hi @bummzack - hmm, good point!  I will have a look into it. 😃

**Comment by srigaux** [comment]
Is there a solution?

**Comment by guyvanbael** [comment]
yeah... since ss4 is using native html, this module is the only way to get datefields working in safari. It would be fantastic for us europeans if it picked up the contentlocale too...

**Comment by bhofstaetter** [comment]
As a **workaround**, I'm loading the required localisation file inside my LeftAndMain extension with the onAfterInit() function.

```php
	public function onAfterInit() {
		Requirements::javascript('https://npmcdn.com/flatpickr@4.5.2/dist/l10n/de.js');
	}
```

Also I have two helper functions to easily create those fields and append the correct config to it

```php
	/**
	 * Returns the matching config for the given field type
	 *
	 * @param string $fieldType Could be DateField, TimeField or DateTimeField
	 *
	 * @return mixed
	 */
	public static function flatpickr_config($fieldType) {
		$calConfigs = Config::inst()->get(LeftAndMain::class, 'calendar_configs');
		return $calConfigs[$fieldType];
	}

	/**
	 * Create DateField, TimeField and DateTimeField with the correct flatpickr config
	 * 
	 * @param $fieldType
	 * @param $fieldName
	 * @param $fieldTitle
	 *
	 * @return bool|string
	 */
	public static function flatpickr_field($fieldType, $fieldName, $fieldTitle) {
		$field = false;

		if ($fieldType == 'DateField') {
			$field = 'SilverStripe\Forms\DateField';
		} else if ($fieldType == 'DateTimeField') {
			$field = 'SilverStripe\Forms\DateTimeField';
		} else if ($fieldType == 'TimeField') {
			$field = 'SilverStripe\Forms\TimeField';
		}

		if ($field) {
			$field = $field::create($fieldName, $fieldTitle);
			$field->setCalendarConfig(self::flatpickr_config($fieldType));
			return $field;
		}
	}
```

This code is located inside a class I named "Toolbox" so to create fields, I'll do

```php
Toolbox::flatpickr_field('DateTimeField, 'Date', 'Datum & Uhrzeit')
```

The configuration is stored in yml, for german fields mine looks like this

```yaml
SilverStripe\Admin\LeftAndMain:
  calendar_highlight_color: '#43536d'
  calendar_configs:
    DateField:
      altInput: true
      allowInput: true
      altFormat: 'd.m.Y'
      dateFormat: 'Y/m/d'
      locale: de
      weekNumbers: true
    DateTimeField:
      altInput: true
      allowInput: true
      time_24hr: true
      altFormat: 'd.m.Y H:i'
      dateFormat: 'Y/m/d H:i'
      locale: de
      weekNumbers: true
    TimeField:
      locale: de,
      time_24hr: true
      allowInput: true
      dateFormat: 'H:i'
      altFormat: 'H:i'
```

Quite sure that's not the nicest solution and a little bit more than just localisation, but perhaps it will help someone ;)

I've also tried to apply this "global" to all of the three fields with an extension of ``CMSPageEditController`` and the use of the ``updateEditForm`` function. This works until the page is saved. Afterwards, the configuration didn't get reapplied and the default config is used. So I switched to the ``Toolbox::flatpickr_field()`` method
